# Generated by Django 6.0.2 on 2026-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='auta/'),
        ),
    ]
