# Generated by Django 6.0.2 on 2026-05-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vypujcka',
            name='celkova_cena',
        ),
        migrations.RemoveField(
            model_name='zakaznik',
            name='cislo_rp',
        ),
        migrations.RemoveField(
            model_name='zamestnanec',
            name='telefon',
        ),
        migrations.AlterField(
            model_name='vypujcka',
            name='stav',
            field=models.CharField(choices=[('cekajici', 'Čeká'), ('schvaleno', 'Schváleno')], default='cekajici', max_length=20),
        ),
        migrations.AlterField(
            model_name='vypujcka',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zamestnanec'),
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
