# Generated by Django 6.0.2 on 2026-05-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('spz', models.CharField(max_length=20)),
                ('denni_sazba', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stav_nadrze', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('cislo_rp', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('pozice', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('celkova_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stav', models.CharField(choices=[('cekajici', 'Čeká na schválení'), ('schvaleno', 'Schváleno'), ('vypujceno', 'Vypůjčeno'), ('ukonceno', 'Ukončeno')], default='cekajici', max_length=20)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auto')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zakaznik')),
                ('zamestnanec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zamestnanec')),
            ],
        ),
    ]
