# Generated by Django 6.0.2 on 2026-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_zakaznik_user_zamestnanec_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vypujcka',
            name='celkova_cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
